import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface ExportData {
    fileName: string;
    projectName?: string;
    documentType?: string | null;
    createdAt: Date;
    issues: Array<{
        severity: string;
        title: string;
        message: string;
        ruleId?: string;
    }>;
    summary: {
        totalIssues: number;
        criticalCount: number;
        warningCount: number;
        infoCount: number;
    };
}

export function exportReportToPDF(data: ExportData) {
    const doc = new jsPDF();
    let yPosition = 20;

    // Header
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.text("안전 점검 보고서", 105, yPosition, { align: "center" });
    yPosition += 10;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("스마트 안전지킴이", 105, yPosition, { align: "center" });
    yPosition += 15;

    // Document Info Box
    doc.setFillColor(240, 240, 240);
    doc.rect(15, yPosition, 180, 40, "F");
    yPosition += 10;

    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text(`파일명: ${data.fileName}`, 20, yPosition);
    yPosition += 7;

    if (data.projectName) {
        doc.setFont("helvetica", "normal");
        doc.text(`프로젝트: ${data.projectName}`, 20, yPosition);
        yPosition += 7;
    }

    if (data.documentType) {
        doc.text(`문서 유형: ${data.documentType}`, 20, yPosition);
        yPosition += 7;
    }

    doc.text(`생성 날짜: ${data.createdAt.toLocaleString('ko-KR')}`, 20, yPosition);
    yPosition += 15;

    // Summary Statistics
    doc.setFillColor(34, 197, 94); // Green
    doc.rect(15, yPosition, 180, 8, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.text("검증 요약", 20, yPosition + 6);
    doc.setTextColor(0, 0, 0);
    yPosition += 15;

    const summaryData = [
        ["총 문제점", data.summary.totalIssues.toString()],
        ["심각한 문제", data.summary.criticalCount.toString()],
        ["경고", data.summary.warningCount.toString()],
        ["정보", data.summary.infoCount.toString()],
    ];

    autoTable(doc, {
        startY: yPosition,
        head: [["항목", "개수"]],
        body: summaryData,
        theme: "grid",
        headStyles: { fillColor: [34, 197, 94] },
        margin: { left: 15, right: 15 },
    });

    yPosition = (doc as any).lastAutoTable.finalY + 15;

    // Issues Table
    if (data.issues.length > 0) {
        doc.setFillColor(239, 68, 68); // Red
        doc.rect(15, yPosition, 180, 8, "F");
        doc.setTextColor(255, 255, 255);
        doc.setFont("helvetica", "bold");
        doc.text("발견된 문제점", 20, yPosition + 6);
        doc.setTextColor(0, 0, 0);
        yPosition += 15;

        const issuesData = data.issues.map((issue, idx) => [
            (idx + 1).toString(),
            getSeverityKorean(issue.severity),
            issue.title,
            issue.message,
        ]);

        autoTable(doc, {
            startY: yPosition,
            head: [["#", "심각도", "제목", "설명"]],
            body: issuesData,
            theme: "striped",
            headStyles: { fillColor: [239, 68, 68] },
            columnStyles: {
                0: { cellWidth: 10 },
                1: { cellWidth: 25 },
                2: { cellWidth: 50 },
                3: { cellWidth: 95 },
            },
            margin: { left: 15, right: 15 },
            styles: {
                fontSize: 9,
                cellPadding: 3,
            },
            didParseCell: (data) => {
                // Color-code severity column
                if (data.column.index === 1 && data.section === "body") {
                    const severity = data.cell.raw as string;
                    if (severity === "심각") {
                        data.cell.styles.textColor = [239, 68, 68];
                        data.cell.styles.fontStyle = "bold";
                    } else if (severity === "경고") {
                        data.cell.styles.textColor = [251, 146, 60];
                        data.cell.styles.fontStyle = "bold";
                    }
                }
            },
        });
    }

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(
            `페이지 ${i} / ${pageCount}`,
            105,
            doc.internal.pageSize.height - 10,
            { align: "center" }
        );
        doc.text(
            "Generated by Smart Safety Guardian",
            105,
            doc.internal.pageSize.height - 5,
            { align: "center" }
        );
    }

    // Download
    const fileName = `${data.projectName ? data.projectName + "_" : ""}${data.fileName.replace(/\.[^/.]+$/, "")}_report.pdf`;
    doc.save(fileName);
}

function getSeverityKorean(severity: string): string {
    const map: Record<string, string> = {
        error: "심각",
        warn: "경고",
        info: "정보",
    };
    return map[severity] || severity;
}
